cluster:
  name: my-cluster
  namespace: kafka
  kafkaVersion: 3.8.0
  metadataVersion: 3.8-IV0
  listeners:
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    default.replication.factor: 3
    min.insync.replicas: 2

controllerNodePool:
  name: controller
  replicas: 3
  storage:
    type: jbod
    volumes:
        type: persistent-claim
        size: 100Gi
        kraftMetadata: shared
        deleteClaim: false

brokerNodePool:
  name: broker
  replicas: 3
  storage:
    type: jbod
    volumes:
        type: persistent-claim
        size: 100Gi
        kraftMetadata: shared
        deleteClaim: false

entityOperator:
  enabled: true
  topicOperator: {}
  userOperator: {}
