{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    strimzi.io/cluster: {{ .cluster }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
{{ toYaml .config | indent 4 }}
---
{{- end }}

